### ISSUE TITLE
Cannot send mails from a French installation

### ISSUE THREAD

**Issue by bforest** [teqnology/alfresco-login-reset-repo#1]
Hi,

Your code doesn't work on a no-english Alfresco.
You're using "childByNamePath" function that is based on the locale (at Alfresco first bootstrap).

Instead using : 

``` javascript
companyhome.childByNamePath("Data Dictionary/Email Templates/custom-email-template/reset-password-email.ftl")
```

You should use 'xpathSearch' function : 

``` javascript
  var mailTemplates = search.xpathSearch('/app:company_home/app:dictionary/app:email_templates/cm:custom-email-template/cm:reset-password-email.ftl');
  if (mailTemplates.length > 0) {
    mail.parameters.template = mailTemplates[0];
  } else {
    mail.parameters.text = "Missing template";
  }
```

"childByNamePath" is used twice in "forgot-password-workflow.post.json.js" and once in "reset-password-workflow.post.json.js".

Regards.

**Comment by teqnology** [comment]
I've updated the source code with the xpathSearch for both reset-password and forgot-password webscripts. Tested and validated, I'd like you to try with the latest -repo.amp and see if it works now. :)

**Comment by atsanna** [comment]
Hi, 
in the source code of "forgotten password-workflow.post.json.js" and "reset-password-workflow.post.json.js". you forgot "cm:" before "forgotten password-email.ftl".

I use Alfresco 5.0.d CE - Italian language

Regards.

**Comment by teqnology** [comment]
Thanks for the hint, I've updated the source code and repackaged the -repo.amp file. The typo should be fixed now and the issue gone. Please let me know if this one can be closed

**Comment by ghost** [comment]
Hi,
First, thanks for your code !
Second, I've got a problem since I changed the language to French :
whenever I try to get instructions when password forgotten I get an error message :
![4E6CB51E](https://user-images.githubusercontent.com/40274016/54990113-3bf60100-4fba-11e9-9d4f-b5a5f35c5d7c.PNG)

Do you have any idea about what's the problemand what I should do ?

Thanks.

**Comment by teqnology** [comment]
Hi buddy,

from the error returned it looks to me like something on your side has a very long name. Did you change any code, or do you have any idea on what could it be that has 407 characters instead of the maximum of 255? I'd need perhaps the complete logs to debug (usually there's a bit more info on where the script got interrupted.

**Comment by ghost** [comment]
Thanks for answering !
Here is the log I got :

ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-2] Exception from executeScript: 03020030 Wrapped Exception (with status template): 03023597 Failed to execute script 'classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js': Localname is too long. Length of 407 exceeds the maximum of 255
org.springframework.extensions.webscripts.WebScriptException: 03020030 Wrapped Exception (with status template): 03023597 Failed to execute script 'classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js': Localname is too long. Length of 407 exceeds the maximum of 255
        at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
        at org.alfresco.repo.web.scripts.RepositoryContainer$4.doWork(RepositoryContainer.java:664)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:668)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:355)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.alfresco.scripts.ScriptException: 03023597 Failed to execute script 'classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js': Localname is too long. Length of 407 exceeds the maximum of 255
        at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:211)
        at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
        at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
        at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
        at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
        ... 38 more
Caused by: java.lang.IllegalArgumentException: Localname is too long. Length of 407 exceeds the maximum of 255
        at org.alfresco.repo.node.db.DbNodeServiceImpl.createNode_aroundBody24(DbNodeServiceImpl.java:375)
        at org.alfresco.repo.node.db.DbNodeServiceImpl$AjcClosure25.run(DbNodeServiceImpl.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
        at org.alfresco.repo.node.db.DbNodeServiceImpl.createNode(DbNodeServiceImpl.java:359)
        at sun.reflect.GeneratedMethodAccessor1113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.alfresco.repo.lock.mem.LockableAspectInterceptor.invoke(LockableAspectInterceptor.java:244)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy23.createNode(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.alfresco.repo.tenant.MultiTNodeServiceInterceptor.invoke(MultiTNodeServiceInterceptor.java:111)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy23.createNode(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.alfresco.repo.service.StoreRedirectorProxyFactory$RedirectorInvocationHandler.invoke(StoreRedirectorProxyFactory.java:231)
        at com.sun.proxy.$Proxy46.createNode(Unknown Source)
        at org.alfresco.repo.node.MLPropertyInterceptor.invoke(MLPropertyInterceptor.java:284)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.enterprise.repo.sync.SyncPropertyInterceptor.invoke(SyncPropertyInterceptor.java:262)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.node.NodeRefPropertyMethodInterceptor.invoke(NodeRefPropertyMethodInterceptor.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy23.createNode(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
        at com.sun.proxy.$Proxy23.createNode(Unknown Source)
        at org.alfresco.repo.security.person.PersonServiceImpl.createPerson(PersonServiceImpl.java:982)
        at org.alfresco.repo.security.person.PersonServiceImpl.createPerson(PersonServiceImpl.java:946)
        at org.alfresco.repo.security.person.PersonServiceImpl.createMissingPerson(PersonServiceImpl.java:871)
        at org.alfresco.repo.security.person.PersonServiceImpl.getPersonImpl(PersonServiceImpl.java:504)
        at org.alfresco.repo.security.person.PersonServiceImpl.getPerson(PersonServiceImpl.java:483)
        at org.alfresco.repo.security.person.PersonServiceImpl.getPerson(PersonServiceImpl.java:440)
        at sun.reflect.GeneratedMethodAccessor671.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.audit.AuditMethodInterceptor.proceedWithAudit(AuditMethodInterceptor.java:256)
        at org.alfresco.repo.audit.AuditMethodInterceptor.proceed(AuditMethodInterceptor.java:216)
        at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:171)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy112.getPerson(Unknown Source)
        at org.alfresco.repo.preference.PreferenceServiceImpl.setPreferences_aroundBody0(PreferenceServiceImpl.java:387)
        at org.alfresco.repo.preference.PreferenceServiceImpl$AjcClosure1.run(PreferenceServiceImpl.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
        at org.alfresco.repo.preference.PreferenceServiceImpl.setPreferences(PreferenceServiceImpl.java:384)
        at org.alfresco.repo.preference.script.ScriptPreferenceService.setPreferences(ScriptPreferenceService.java:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_com_androgogic_login_forgot_password_forgot_password_workflow_post_json_js_134._c_main_14(classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js:184)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_com_androgogic_login_forgot_password_forgot_password_workflow_post_json_js_134.call(classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_com_androgogic_login_forgot_password_forgot_password_workflow_post_json_js_134._c_script_0(classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js:234)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_com_androgogic_login_forgot_password_forgot_password_workflow_post_json_js_134.call(classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_com_androgogic_login_forgot_password_forgot_password_workflow_post_json_js_134.call(classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_com_androgogic_login_forgot_password_forgot_password_workflow_post_json_js_134.exec(classpath*:alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
        ... 43 more

**Comment by teqnology** [comment]
Have you made any changes to the code that is hosted in this repo? And have you tried different users and changing from email to a username? Is the error still the same, always?

**Comment by teqnology** [comment]
and another relevant question, what Alfresco are you on

**Comment by teqnology** [comment]
This is where that error message appears to be coming from, `DbNodeServiceImpl.java`:
```
if(assocQName.getLocalName().length() > QName.MAX_LENGTH)
        {
            throw new IllegalArgumentException("Localname is too long. Length of " + 
                 assocQName.getLocalName().length() + " exceeds the maximum of " + QName.MAX_LENGTH);
        }

```

You have a local french string that is longer than the accepted maximum QName.MAX_LENGTH (which is set to 255 by default). I can't help you find the string, as I don't work in French, but it's definitely something in your local environment.

Hope this helps you debugging it.
Cheers

**Comment by ghost** [comment]
Thx again for your answer, 
- alfresco version is 5.2.4.
- no change of your code has been done.
- when trying with username it works fine.

Do you think it's ok if I just change the max length ?

**Comment by teqnology** [comment]
I don't think you can change it unless you change the Java code of the class I posted in the previous reply (but I'm not entirely sure about that).
 
But I did a bit of digging and these are my findings: 
The issue appears to be when invoking the createNode within the DbNodeServiceImpl.java class. the QName, the only two things that create something when requesting a new password is a workflow and setting preferences within the user. This latter one appears to be the culprit:
If you go here:

> https://hostname/alfresco/service/api/people/testuser/preferences (change testuser with the user you're failing to update the pwd for)

and you'll see an object that looks similar to this:

`{"com": {"androgogic": {"login": {"activiti": "", "key": ""}}}, "org": {"alfresco": {"share": {"documentList": {"viewRendererName": "simple"}, "searchList": {"viewRendererName": "detailed"}}}}}

When I tried to update the preferences through a JS snippet it failed for me too (giving me the LocalName too long error). I reckon it's worth investigating in this direction, probably worth a crack going to 

> /alfresco/service/index/uri/api/people/%7Buserid%7D/preferences

and DELETE the preferences all together, and then try the reset pwd again.
Not sure why the localisation change messes up with this. If I find some time I'll have a look, in the meanwhile you can do it yourself, the JS is fairly easy, this is the code that is causing the error: 

`
`preferenceService.setPreferences(user.properties.userName, {com:{androgogic:{login:{key:key,activiti:activitiId}}}});
`
or for the array of found users with the same email:

`preferenceService.setPreferences(user, {com:{androgogic:{login:{key:key,activiti:activitiId}}}});
`

**Comment by teqnology** [comment]
Hey sorry man, I think I overlooked my pull requests. 
This error was reproduced and fixed by jkondrat, but I totally didn't see it.

I've manage to push everything tonight, so let me know if the error still appears, but it should be gone now.

**Comment by ghost** [comment]
Thanks again, I'll try soon ant let you know what happen !

**Comment by ghost** [comment]
Seems to work fine no problem anymore ! ;)
